(function(){
  function currentScriptRoot(){
    const scripts=[...document.scripts];
    const me=scripts.find(s=>/docs-shell\.js(?:\?|$)/.test(s.src));
    return me?new URL('../../',me.src):new URL('../../',location.href);
  }
  const root=currentScriptRoot();
  const manifest=(window.TRAINING_SITE_MANIFEST||{}).modules||[];
  const program=document.body.dataset.program||'FRC';
  const slug=document.body.dataset.moduleSlug||'';
  const meta=manifest.find(m=>m.program===program&&m.slug===slug)||manifest.find(m=>new URL(m.path,root).pathname===location.pathname)||{};
  const completeKey='5041-training-complete:'+(meta.path||location.pathname);

  function isDone(m){return localStorage.getItem('5041-training-complete:'+m.path)==='1'}
  function markDone(){ if(meta.path) localStorage.setItem(completeKey,'1'); updateDoneStates(); }
  function updateDoneStates(){document.querySelectorAll('[data-module-path]').forEach(a=>{const m=manifest.find(x=>x.path===a.dataset.modulePath);if(m)a.classList.toggle('done',isDone(m))})}
  function make(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!=null)el.textContent=text;return el}
  function link(href,cls,text){const a=make('a',cls,text);a.href=href;return a}
  function buildHeader(){const h=make('header','docs-site-header');const inner=make('div','docs-header-inner');const brand=link(new URL('index.html',root),'docs-brand');const img=document.createElement('img');img.src=new URL('site-assets/img/5041teamlogo.png',root);img.alt='5041 CyBears';brand.append(img);const copy=make('span','docs-brand-copy');copy.append(make('span','docs-brand-title','5041 CyBears Training'),make('span','docs-brand-subtitle','Documentation & Certification'));brand.append(copy);const menu=make('button','docs-menu-button','Menu');menu.type='button';menu.addEventListener('click',()=>document.body.classList.toggle('docs-nav-open'));inner.append(menu,brand,make('span','docs-header-spacer'),make('span','docs-program-pill',program+' Training'));h.append(inner);return h}
  function buildSidebar(){const side=make('aside','docs-sidebar');const search=document.createElement('input');search.className='docs-search';search.type='search';search.placeholder='Filter modules…';search.setAttribute('aria-label','Filter training modules');side.append(search);['FRC','FTC'].forEach(p=>{const group=make('div','docs-nav-group');group.dataset.program=p;group.append(make('div','docs-nav-heading',p+' modules'));manifest.filter(m=>m.program===p).forEach(m=>{const a=link(new URL(m.path,root),'docs-nav-link',m.title);a.dataset.modulePath=m.path;if(m.path===meta.path)a.classList.add('active');if(isDone(m))a.classList.add('done');group.append(a)});side.append(group)});search.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();side.querySelectorAll('.docs-nav-link').forEach(a=>a.hidden=q&&!a.textContent.toLowerCase().includes(q));});side.addEventListener('click',e=>{if(e.target.closest('a'))document.body.classList.remove('docs-nav-open')});return side}
  function prepareSections(){const sections=[...document.querySelectorAll('.reveal .slides section')];let n=0;sections.forEach(s=>{const hasChild=!!s.querySelector(':scope > section');s.classList.add(hasChild?'docs-section-group':'docs-page-section');if(!hasChild&&!s.id)s.id='section-'+(++n)});return sections.filter(s=>s.classList.contains('docs-page-section'))}
  function sectionLabel(s){const tag=s.querySelector(':scope > .tag');const h=s.querySelector(':scope > h1,:scope > h2,:scope > h3');let t=(tag&&tag.textContent.trim())||(h&&h.textContent.trim())||'';if(!t&&s.id==='complete')t='Completion Certificate';if(!t&&s.id&&s.id.startsWith('quiz-q'))t='Quiz';return t.replace(/\s+/g,' ').trim()}
  function buildToc(leaves){const toc=make('aside','docs-toc');toc.append(make('div','docs-toc-title','On this page'));const seen=new Set();leaves.forEach(s=>{if(s.id&&/^quiz-q\d+$/i.test(s.id))return;const label=sectionLabel(s);if(!label||seen.has(label))return;seen.add(label);const a=link('#'+s.id,'',label);toc.append(a)});return toc}
  function addLockBanner(){const complete=document.getElementById('complete');if(!complete)return;let banner=complete.querySelector('.docs-lock-banner');if(!banner){banner=make('div','docs-lock-banner','Certificate locked — complete the quiz and earn the required passing score to unlock it.');complete.insertBefore(banner,complete.firstChild)}const sync=()=>{if(!complete.classList.contains('locked'))markDone()};new MutationObserver(sync).observe(complete,{attributes:true,attributeFilter:['class']});sync()}
  function addProgress(leaves){const box=make('div','docs-progress');const label=make('span','','Reading progress');const track=make('span','docs-progress-bar');const fill=make('span');track.append(fill);const pct=make('span','','0%');box.append(label,track,pct);const update=()=>{const article=document.querySelector('.docs-article');if(!article)return;const rect=article.getBoundingClientRect();const total=Math.max(1,article.scrollHeight-innerHeight*.45);const scrolled=Math.min(total,Math.max(0,-rect.top+100));const p=Math.round(scrolled/total*100);fill.style.width=p+'%';pct.textContent=p+'%'};addEventListener('scroll',update,{passive:true});setTimeout(update,50);return box}
  function nextPrev(){const filtered=manifest.filter(m=>m.program===program);const i=filtered.findIndex(m=>m.path===meta.path);const wrap=make('nav','docs-nextprev');const prev=i>0?filtered[i-1]:null,next=i>=0&&i<filtered.length-1?filtered[i+1]:null;const build=(m,dir)=>{if(!m)return make('span');const a=link(new URL(m.path,root),'',m.title);const small=make('small','',dir);a.prepend(small);return a};wrap.append(build(prev,'Previous module'),build(next,'Next module'));return wrap}
  function run(){document.body.classList.add('docs-module');const reveal=document.querySelector('.reveal');if(!reveal)return;const leaves=prepareSections();const header=buildHeader(),sidebar=buildSidebar();const layout=make('div','docs-layout');const main=make('main','docs-main');const article=make('article','docs-article');const crumbs=make('div','docs-breadcrumbs');crumbs.append(link(new URL('index.html',root),'','Training Home'),document.createTextNode(' / '),link(new URL(program==='FRC'?'FRC-trainings/frc-trainings.html':'FTC-training/ftc-trainings.html',root),'',program),document.createTextNode(' / '+(meta.title||document.title)));main.append(crumbs,make('h1','docs-page-title',meta.title||document.title));if(meta.description)main.append(make('p','docs-lead',meta.description));main.append(addProgress(leaves));reveal.parentNode.insertBefore(article,reveal);article.append(reveal);main.append(article,nextPrev());layout.append(sidebar,main,buildToc(leaves));document.body.prepend(header);document.body.insertBefore(layout,header.nextSibling);addLockBanner();updateDoneStates();
    const anchors=[...document.querySelectorAll('.docs-toc a')]; if('IntersectionObserver'in window){const obs=new IntersectionObserver(es=>{const e=es.filter(x=>x.isIntersecting)[0];if(!e)return;anchors.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))},{rootMargin:'-20% 0px -70% 0px',threshold:0});leaves.forEach(s=>obs.observe(s));}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
